import type { WorkspaceSessionViewsApi } from "@/components/app/hooks/useWorkspaceSessionViews";
import type { AppView, ResolvedTheme, ThemeMode, WindowUiState } from "@/components/app/types";
import type { TitleBarWorkspaceQuickSearchConfig } from "@/components/app/types/titlebarWorkspaceSearch.types";
import type { AppState, InstalledIde, WorkspaceSplitViewCollection } from "@shared/appTypes";

export type TitleBarBuildDeps = {
  activeSplitViewCollection: WorkspaceSplitViewCollection;
  activeView: AppView;
  canOpenProjectInIde: boolean;
  defaultIdeId: string | null;
  focusNextSessionTab: () => void;
  focusPreviousSessionTab: () => void;
  handleOpenProjectInIde: (ideId: string) => void;
  handleOpenRecentWorkspace: (projectRoot: string, projectName: string) => void | Promise<void>;
  handleSubmitIssue: () => void;
  hasActiveWorkspace: boolean;
  installedIdes: InstalledIde[];
  isChangesSidebarCollapsed: boolean;
  isLoadingInstalledIdes: boolean;
  isWorkspaceSidebarCollapsed: boolean;
  sidebarsSwapped: boolean;
  onAddRemoteWorkspace: () => void;
  onFocusLocalTerminalDock: () => void;
  onOpenAbout: () => void;
  onOpenKeyboardShortcuts: () => void;
  onToggleChangesSidebar: () => void;
  onToggleLocalTerminalDock: () => void;
  onToggleWorkspaceSidebar: () => void;
  openAddWorkspace: () => void;
  openCreateAgent: () => void;
  openCreateBrowser: () => void;
  openCreateTerminal: () => void;
  openStartupDependencies: () => void;
  onCloseWorkspace: () => void;
  onOpenSettings: () => void;
  onRefreshWorkspace: () => void;
  preferredIde: InstalledIde | null;
  recentWorkspaces: AppState["recentProjects"];
  resolvedTheme: ResolvedTheme;
  snapshotProject: AppState["project"];
  themeMode: ThemeMode;
  toggleTheme: () => void;
  useMacTitleBarChrome: boolean;
  windowUiState: WindowUiState;
  workspaceQuickSearch: TitleBarWorkspaceQuickSearchConfig | null;
  workspaceSessionViews: Pick<WorkspaceSessionViewsApi, "activeViewId" | "setActiveViewId" | "createView">;
};
