import type { NoteListEntry, SpecListEntry, TaskListEntry } from "@/components/app/types/component.types";
import type { WorkspaceSidebarAgentContextMenuState } from "@/components/app/types/workspaceSidebarAgentContextMenu.types";
import type { AgentSession } from "@shared/appTypes";
import type { Dispatch, MouseEvent, RefObject, SetStateAction } from "react";

export type UseWorkspaceSidebarOverlaysResult = {
  now: number;
  activeSessionPopoverId: string | null;
  setActiveSessionPopoverId: Dispatch<SetStateAction<string | null>>;
  activeTaskMenu: { task: TaskListEntry; top: number; left: number } | null;
  activeSpecMenu: { spec: SpecListEntry; top: number; left: number } | null;
  activeNoteMenu: { note: NoteListEntry; top: number; left: number } | null;
  activeWorkspaceMenu: { workspaceId: string; top: number; left: number } | null;
  activeAgentMenu: WorkspaceSidebarAgentContextMenuState | null;
  taskMenuRef: RefObject<HTMLDivElement | null>;
  specMenuRef: RefObject<HTMLDivElement | null>;
  noteMenuRef: RefObject<HTMLDivElement | null>;
  workspaceMenuRef: RefObject<HTMLDivElement | null>;
  agentMenuRef: RefObject<HTMLDivElement | null>;
  openTaskMenu: (task: TaskListEntry, event: MouseEvent<HTMLButtonElement>) => void;
  openSpecMenu: (spec: SpecListEntry, event: MouseEvent<HTMLButtonElement>) => void;
  openNoteMenu: (note: NoteListEntry, event: MouseEvent<HTMLButtonElement>) => void;
  openWorkspaceMenu: (workspaceId: string, event: MouseEvent<HTMLDivElement | HTMLButtonElement>) => void;
  openAgentSessionMenu: (workspaceId: string, agent: AgentSession, pullRequestWebUrl: string | null, event: MouseEvent<Element>) => void;
  openSessionPopover: (sessionId: string) => void;
  scheduleSessionPopoverClose: () => void;
  setActiveTaskMenu: Dispatch<SetStateAction<{ task: TaskListEntry; top: number; left: number } | null>>;
  setActiveSpecMenu: Dispatch<SetStateAction<{ spec: SpecListEntry; top: number; left: number } | null>>;
  setActiveNoteMenu: Dispatch<SetStateAction<{ note: NoteListEntry; top: number; left: number } | null>>;
  setActiveWorkspaceMenu: Dispatch<SetStateAction<{ workspaceId: string; top: number; left: number } | null>>;
  setActiveAgentMenu: Dispatch<SetStateAction<WorkspaceSidebarAgentContextMenuState | null>>;
};
