import type { SettingsSearchEntry } from "@/components/app/types/settingsSearch.types";

export const SETTINGS_SEARCH_INDEX: readonly SettingsSearchEntry[] = [
  { group: "appearance", title: "Sidebar layout", keywords: ["swap", "left", "right", "projects", "changes"] },
  { group: "appearance", title: "Color Theme", keywords: ["dark", "light", "system", "mode"] },
  { group: "appearance", title: "Accent Color", keywords: ["highlight", "colour", "primary"] },
  { group: "appearance", title: "UI Font", keywords: ["typeface", "inter", "geist"] },
  { group: "appearance", title: "File Editor Theme", keywords: ["monaco", "code", "syntax"] },
  { group: "appearance", title: "Terminal Theme", keywords: ["palette", "colors"] },
  { group: "appearance", title: "Terminal Font", keywords: ["monospace"] },
  { group: "general", title: "Default IDE", keywords: ["editor", "vscode", "cursor", "open"] },
  { group: "general", title: "Project State Location", keywords: [".nora", "tasks", "specs", "notes", "storage"] },
  { group: "general", title: "Default Agent Launch Target", keywords: ["new agent", "worktree"] },
  { group: "general", title: "Agent Completion Notifications", keywords: ["notify", "alert", "done"] },
  { group: "workbench", title: "Projects Sidebar", keywords: ["collapsed", "layout"] },
  { group: "workbench", title: "Changes Panel", keywords: ["collapsed", "git", "diff"] },
  { group: "workbench", title: "Agent CLIs Section", keywords: ["collapsed", "sidebar"] },
  { group: "workbench", title: "Specs Section", keywords: ["collapsed", "sidebar"] },
  { group: "workbench", title: "Local Terminal Dock", keywords: ["collapsed", "bottom"] },
  { group: "workbench", title: "Default Split View Grid", keywords: ["layout", "panes"] },
  { group: "workbench", title: "Remember Last Split View", keywords: ["restore", "panes"] },
  { group: "workbench", title: "Confirm Split View Delete", keywords: ["confirmation", "panes"] },
  { group: "workbench", title: "Project Session Tabs", keywords: ["tabs", "agents", "terminals"] },
  { group: "terminal", title: "Default Shell", keywords: ["zsh", "bash", "powershell"] },
  { group: "terminal", title: "Quick Launch Defaults", keywords: ["new terminal"] },
  { group: "terminal", title: "Terminal presets", keywords: ["commands", "scripts"] },
  { group: "browser", title: "Auto-open Browser On New Port", keywords: ["localhost", "url", "dev server"] },
  { group: "browser", title: "Import Chrome Cookies", keywords: ["login", "session", "profile"] },
  { group: "cli", title: "Preferred Agent CLI", keywords: ["claude", "codex", "cursor", "default agent"] },
  { group: "agentUsage", title: "Claude Code", keywords: ["tokens", "usage"] },
  { group: "agentUsage", title: "Codex", keywords: ["tokens", "usage"] },
  { group: "skills", title: "Find skills", keywords: ["search", "registry"] },
  { group: "skills", title: "Install by reference", keywords: ["install", "skill"] },
  { group: "skills", title: "Installed skills", keywords: ["remove", "skill"] },
  { group: "integrations", title: "GitHub Token", keywords: ["forge", "pull requests", "access token"] },
  { group: "integrations", title: "GitLab Token", keywords: ["forge", "merge requests", "access token"] },
  { group: "integrations", title: "Vercel Token", keywords: ["deployments", "access token"] },
  { group: "ai", title: "Simple AI Tasks", keywords: ["commit message", "local", "cloud"] },
  { group: "ai", title: "Local Model", keywords: ["llama", "gguf", "on-device"] },
  { group: "ai", title: "Preferred Provider", keywords: ["openai", "anthropic", "google"] },
  { group: "ai", title: "Commit Message Model", keywords: ["model", "git"] },
  { group: "ai", title: "OpenAI API Key", keywords: ["gpt", "key"] },
  { group: "ai", title: "Google API Key", keywords: ["gemini", "key"] },
  { group: "ai", title: "Anthropic API Key", keywords: ["claude", "key"] },
  { group: "voice", title: "Dictation Engine", keywords: ["microphone", "transcription", "speech"] },
  { group: "voice", title: "Local Whisper", keywords: ["whisper.cpp", "offline", "speech"] },
  { group: "privacy", title: "Usage Analytics", keywords: ["telemetry", "tracking", "diagnostics"] },
  { group: "system", title: "Hardware Acceleration", keywords: ["gpu", "rendering"] },
  { group: "dev", title: "Onboarding Flow", keywords: ["first run"] },
  { group: "dev", title: "Preview Toast Styles", keywords: ["toast", "notification"] }
];
