import { getWorkspaceFileExtension, getWorkspaceFileLeafName } from "@/lib/workspaceFileIconKind";
import {
  SiApachegroovy,
  SiApple,
  SiAssemblyscript,
  SiC,
  SiClojure,
  SiCmake,
  SiCplusplus,
  SiCss,
  SiDart,
  SiDotnet,
  SiElixir,
  SiErlang,
  SiFsharp,
  SiGnubash,
  SiGo,
  SiGradle,
  SiGraphql,
  SiHaskell,
  SiHomebrew,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiJulia,
  SiKotlin,
  SiLess,
  SiLua,
  SiNim,
  SiOpenjdk,
  SiPerl,
  SiPhp,
  SiPostcss,
  SiPython,
  SiR,
  SiReact,
  SiRuby,
  SiRust,
  SiSass,
  SiScala,
  SiSolidity,
  SiSqlite,
  SiStylus,
  SiSvelte,
  SiSwift,
  SiTypescript,
  SiVagrant,
  SiVuedotjs,
  SiWebassembly,
  SiXml,
  SiZig
} from "@icons-pack/react-simple-icons";

export type WorkspaceCodeSimpleIcon = typeof SiTypescript;

const CODE_BASENAME_ICONS: Readonly<Record<string, WorkspaceCodeSimpleIcon>> = {
  berksfile: SiRuby,
  brewfile: SiHomebrew,
  capfile: SiRuby,
  "cmakelists.txt": SiCmake,
  dangerfile: SiRuby,
  fastfile: SiRuby,
  gemfile: SiRuby,
  jenkinsfile: SiJenkins,
  podfile: SiRuby,
  rakefile: SiRuby,
  vagrantfile: SiVagrant
};

const CODE_EXTENSION_ICONS: Readonly<Record<string, WorkspaceCodeSimpleIcon>> = {
  asm: SiAssemblyscript,
  c: SiC,
  cjs: SiJavascript,
  cc: SiCplusplus,
  clj: SiClojure,
  cljc: SiClojure,
  cljs: SiClojure,
  cpp: SiCplusplus,
  cs: SiDotnet,
  css: SiCss,
  cts: SiTypescript,
  cxx: SiCplusplus,
  dart: SiDart,
  edn: SiClojure,
  erl: SiErlang,
  ex: SiElixir,
  exs: SiElixir,
  fs: SiFsharp,
  fsi: SiFsharp,
  fsx: SiFsharp,
  go: SiGo,
  gradle: SiGradle,
  graphql: SiGraphql,
  gql: SiGraphql,
  groovy: SiApachegroovy,
  h: SiC,
  hh: SiCplusplus,
  hpp: SiCplusplus,
  hrl: SiErlang,
  hs: SiHaskell,
  htm: SiHtml5,
  html: SiHtml5,
  hxx: SiCplusplus,
  java: SiOpenjdk,
  jl: SiJulia,
  js: SiJavascript,
  jsx: SiReact,
  kt: SiKotlin,
  kts: SiKotlin,
  lhs: SiHaskell,
  less: SiLess,
  lua: SiLua,
  m: SiApple,
  mm: SiApple,
  mjs: SiJavascript,
  mts: SiTypescript,
  nim: SiNim,
  php: SiPhp,
  phtml: SiPhp,
  pls: SiSqlite,
  py: SiPython,
  pyi: SiPython,
  pyw: SiPython,
  r: SiR,
  rake: SiRuby,
  rb: SiRuby,
  rs: SiRust,
  s: SiAssemblyscript,
  sass: SiSass,
  scala: SiScala,
  sc: SiScala,
  scss: SiSass,
  sh: SiGnubash,
  bash: SiGnubash,
  zsh: SiGnubash,
  fish: SiGnubash,
  sol: SiSolidity,
  styl: SiStylus,
  svelte: SiSvelte,
  swift: SiSwift,
  ts: SiTypescript,
  tsx: SiReact,
  vue: SiVuedotjs,
  wast: SiWebassembly,
  wat: SiWebassembly,
  xhtml: SiHtml5,
  xml: SiXml,
  xsd: SiXml,
  xslt: SiXml,
  zig: SiZig,
  pcss: SiPostcss
};

export function getWorkspaceCodeSimpleIcon(path: string): WorkspaceCodeSimpleIcon | null {
  const baseLower = getWorkspaceFileLeafName(path).toLowerCase();
  const fromBasename = CODE_BASENAME_ICONS[baseLower];
  if (fromBasename) {
    return fromBasename;
  }
  const ext = getWorkspaceFileExtension(path);
  if (!ext) {
    return null;
  }
  if (ext === "pl" || ext === "pm") {
    return SiPerl;
  }
  return CODE_EXTENSION_ICONS[ext] ?? null;
}
