import type {
  UseAppRootWorkspaceSidebarSourcesArgs,
  UseAppRootWorkspaceSidebarSourcesResult
} from "@/components/app/types/useAppRootWorkspaceSidebarSources.types";
import { useCanonicalAppSnapshot } from "@/components/app/hooks/useAppDomainState";
import { useMemo } from "react";

export function useAppRootWorkspaceSidebarSources({
  agentsNeedingAttention,
  collapsedWorkspaceIds,
  focusWorkspaceAiChatTab,
  focusWorkspaceWithRecovery,
  focusedAgent,
  focusedTerminal,
  focusedWorkspace,
  githubToken,
  gitlabHost,
  gitlabToken,
  handleChooseWorkspaceAtPath,
  handleOpenWorkspaceBrowser,
  handleRemoveWorkspace,
  isChatbotsSectionCollapsed,
  isCliSectionCollapsed,
  isNoteBrowserOpen,
  isPortsSectionCollapsed,
  isRemoteMountsSectionCollapsed,
  isSpecBrowserOpen,
  isTaskBoardOpen,
  isWorkspaceSidebarCollapsed,
  launchTerminalInWorkspace,
  openAiChatFromSidebar,
  openSettingsPage,
  openAddWorkspaceModal,
  removingWorkspaceRoots,
  resolveInstallCommand,
  safely,
  setCollapsedWorkspaceIds,
  setFileEditorState,
  setIsCenterDiffExpanded,
  setIsChatbotsSectionCollapsed,
  setIsCliSectionCollapsed,
  setIsPortsSectionCollapsed,
  setIsRemoteMountsSectionCollapsed,
  setIsWorkspaceSidebarCollapsed,
  setWorkspaceSessionActiveViewId,
  activeWorkspaceContentTab,
  terminalPresets,
  terminalQuickLaunchDefaults,
  uiCommands,
  uiState,
  workspaceNotes,
  workspaceSpecs,
  workspaceTasks
}: UseAppRootWorkspaceSidebarSourcesArgs): UseAppRootWorkspaceSidebarSourcesResult {
  const snapshot = useCanonicalAppSnapshot();
  return useMemo(() => {
    if (!snapshot) {
      return null;
    }

    return {
      agentsNeedingAttention,
      collapsedWorkspaceIds,
      focusWorkspaceAiChatTab,
      focusWorkspaceWithRecovery,
      focusedAgent,
      focusedTerminal,
      focusedWorkspace,
      githubToken,
      gitlabHost,
      gitlabToken,
      handleChooseWorkspaceAtPath,
      handleOpenWorkspaceBrowser,
      handleRemoveWorkspace,
      isChatbotsSectionCollapsed,
      isCliSectionCollapsed,
      isNoteBrowserOpen,
      isPortsSectionCollapsed,
      isRemoteMountsSectionCollapsed,
      isSpecBrowserOpen,
      isTaskBoardOpen,
      isWorkspaceSidebarCollapsed,
      launchTerminalInWorkspace,
      openAiChatFromSidebar,
      openSettingsPage,
      openAddWorkspaceModal,
      removingWorkspaceRoots,
      resolveInstallCommand,
      safely,
      setCollapsedWorkspaceIds,
      setFileEditorState,
      setIsCenterDiffExpanded,
      setIsChatbotsSectionCollapsed,
      setIsCliSectionCollapsed,
      setIsPortsSectionCollapsed,
      setIsRemoteMountsSectionCollapsed,
      setIsWorkspaceSidebarCollapsed,
      setWorkspaceSessionActiveViewId,
      activeWorkspaceContentTab,
      activeProjectId: snapshot?.project?.id ?? null,
      agentCatalog: snapshot?.agentCatalog ?? [],
      terminalPresets,
      terminalQuickLaunchDefaults,
      uiCommands: {
        clearBrowserAndForgeFocus: uiCommands.clearBrowserAndForgeFocus,
        clearSessionTabFocus: uiCommands.clearSessionTabFocus,
        openCreateAgentDialog: uiCommands.openCreateAgentDialog,
        openCreateTerminalDialog: uiCommands.openCreateTerminalDialog,
        openResetWorkspacesDialog: uiCommands.openResetWorkspacesDialog,
        openWorkspaceTerminalPresetsDialog: uiCommands.openWorkspaceTerminalPresetsDialog,
        setDestroyAgentId: uiCommands.setDestroyAgentId,
        setInstallCommandDraft: uiCommands.setInstallCommandDraft
      },
      workspaceNotes,
      workspaceSidebarUiState: {
        aiChatTabs: uiState.aiChatTabs,
        focusedAiChatTabId: uiState.focusedAiChatTabId,
        focusedBrowserTabId: uiState.focusedBrowserTabId,
        focusedForgeViewerTabId: uiState.focusedForgeViewerTabId,
        installCommandDrafts: uiState.installCommandDrafts
      },
      workspaceSpecs,
      workspaceTasks
    };
  }, [
    agentsNeedingAttention,
    collapsedWorkspaceIds,
    focusWorkspaceAiChatTab,
    focusWorkspaceWithRecovery,
    focusedAgent,
    focusedTerminal,
    focusedWorkspace,
    githubToken,
    gitlabHost,
    gitlabToken,
    handleChooseWorkspaceAtPath,
    handleOpenWorkspaceBrowser,
    handleRemoveWorkspace,
    isChatbotsSectionCollapsed,
    isCliSectionCollapsed,
    isNoteBrowserOpen,
    isPortsSectionCollapsed,
    isRemoteMountsSectionCollapsed,
    isSpecBrowserOpen,
    isTaskBoardOpen,
    isWorkspaceSidebarCollapsed,
    launchTerminalInWorkspace,
    openAiChatFromSidebar,
    openSettingsPage,
    openAddWorkspaceModal,
    removingWorkspaceRoots,
    resolveInstallCommand,
    safely,
    setCollapsedWorkspaceIds,
    setFileEditorState,
    setIsCenterDiffExpanded,
    setIsChatbotsSectionCollapsed,
    setIsCliSectionCollapsed,
    setIsPortsSectionCollapsed,
    setIsRemoteMountsSectionCollapsed,
    setIsWorkspaceSidebarCollapsed,
    setWorkspaceSessionActiveViewId,
    activeWorkspaceContentTab,
    snapshot,
    terminalPresets,
    terminalQuickLaunchDefaults,
    uiCommands,
    uiState.aiChatTabs,
    uiState.focusedAiChatTabId,
    uiState.focusedBrowserTabId,
    uiState.focusedForgeViewerTabId,
    uiState.installCommandDrafts,
    workspaceNotes,
    workspaceSpecs,
    workspaceTasks
  ]);
}
