import type {
  UseAppRootModalExtrasSourcesArgs,
  UseAppRootModalExtrasSourcesResult
} from "@/components/app/types/useAppRootModalExtrasSources.types";
import { useMemo } from "react";

export function useAppRootModalExtrasSources(
  sources: UseAppRootModalExtrasSourcesArgs
): UseAppRootModalExtrasSourcesResult {
  const {
    agentPendingDestroy,
    setForgeOAuthDevicePrompt,
    setIsBrowserCookieImportPromptOpen,
    setSelectedChromeCookieProfileId,
    setIsCreatePullRequestDialogOpen,
    handleCreateAgentFromDialog,
    forgeOAuthDevicePrompt,
    shouldShowStartupDependenciesDialog,
    effectiveStartupDependencyReport,
    isStartupDependencyDialogBusy,
    startupDependencyInstallTargetId,
    startupDependencyInstallErrorMessage,
    simulatedMissingDependencyIds,
    handleStartupDependenciesDialogOpenChange,
    installStartupDependencyWithRefresh,
    copyStartupDependencyInstructions,
    toggleSimulatedMissingDependency,
    clearSimulatedMissingDependencies,
    reloadStartupDependencyReport,
    workspaceTerminalPresetProject,
    saveWorkspaceTerminalPresets,
    isCreatePullRequestDialogOpen,
    handleChooseLocalWorkspace,
    isLinuxAptSetupDialogOpen,
    linuxAptSetupStatus,
    isInstallingLinuxAptUpdates,
    linuxAptSetupErrorMessage,
    closeLinuxAptSetupDialog,
    installLinuxAptUpdates,
    handleCopyLinuxAptManualCommands,
    isBrowserCookieImportPromptOpen,
    chromeCookieProfiles,
    selectedChromeCookieProfileId,
    isLoadingChromeCookieProfiles,
    isImportingChromeBrowserData,
    updateBrowserPreferences,
    loadChromeCookieProfiles,
    runChromeBrowserDataImport,
    isAnalyticsConsentDialogOpen,
    allowAnalyticsConsent,
    declineAnalyticsConsent,
    workspaceSwitcherEntries
  } = sources;

  return useMemo(() => sources, [
    agentPendingDestroy,
    setForgeOAuthDevicePrompt,
    setIsBrowserCookieImportPromptOpen,
    setSelectedChromeCookieProfileId,
    setIsCreatePullRequestDialogOpen,
    handleCreateAgentFromDialog,
    forgeOAuthDevicePrompt,
    shouldShowStartupDependenciesDialog,
    effectiveStartupDependencyReport,
    isStartupDependencyDialogBusy,
    startupDependencyInstallTargetId,
    startupDependencyInstallErrorMessage,
    simulatedMissingDependencyIds,
    handleStartupDependenciesDialogOpenChange,
    installStartupDependencyWithRefresh,
    copyStartupDependencyInstructions,
    toggleSimulatedMissingDependency,
    clearSimulatedMissingDependencies,
    reloadStartupDependencyReport,
    workspaceTerminalPresetProject,
    saveWorkspaceTerminalPresets,
    isCreatePullRequestDialogOpen,
    handleChooseLocalWorkspace,
    isLinuxAptSetupDialogOpen,
    linuxAptSetupStatus,
    isInstallingLinuxAptUpdates,
    linuxAptSetupErrorMessage,
    closeLinuxAptSetupDialog,
    installLinuxAptUpdates,
    handleCopyLinuxAptManualCommands,
    isBrowserCookieImportPromptOpen,
    chromeCookieProfiles,
    selectedChromeCookieProfileId,
    isLoadingChromeCookieProfiles,
    isImportingChromeBrowserData,
    updateBrowserPreferences,
    loadChromeCookieProfiles,
    runChromeBrowserDataImport,
    isAnalyticsConsentDialogOpen,
    allowAnalyticsConsent,
    declineAnalyticsConsent,
    workspaceSwitcherEntries
  ]);
}
